# -*- coding: utf-8 -*-
# flake8: noqa

from __future__ import absolute_import, print_function

from collections import OrderedDict
from datetime import datetime
from DateTime import DateTime
from imio.helpers.cache import get_current_user_id
from imio.helpers.cache import get_plone_groups_for_user
from imio.helpers.cache import invalidate_cachekey_volatile_for
from imio.helpers.content import add_to_annotation
from imio.helpers.content import del_from_annotation
from imio.helpers.content import get_from_annotation
from imio.helpers.content import get_user_fullname
from imio.helpers.content import object_values
from imio.helpers.content import pop_from_annotation
from imio.helpers.content import set_to_annotation
from imio.helpers.date import formatDate
from imio.helpers.date import wordizeDate
from imio.helpers.workflow import update_role_mappings_for
from imio.helpers.xhtml import removeCssClasses
from imio.helpers.xhtml import unescape_html
from imio.history.utils import getLastWFAction
from Products.CPUtils.Extensions.utils import fileSize
from Products.CPUtils.Extensions.utils import tobytes
from plonemeeting.portal.browser.meeting import get_default_attendees
from plonemeeting.portal.browser.meeting import get_default_signatories
from plonemeeting.portal.browser.meeting import get_default_voters
from plonemeeting.portal.browser.views import is_all_count
from plonemeeting.portal.browser.views import print_votes
from plonemeeting.portal.ftw_labels.utils import get_labels
from plonemeeting.portal.utils import cleanMemoize
from plonemeeting.portal.utils import cropHTML
from plonemeeting.portal.utils import down_or_up_wf
from plonemeeting.portal.utils import escape
from plonemeeting.portal.utils import field_is_empty
from plonemeeting.portal.utils import fieldIsEmpty
from plonemeeting.portal.utils import get_annexes
from plonemeeting.portal.utils import get_attendee_short_title
from plonemeeting.portal.utils import get_gn_position_name
from plonemeeting.portal.utils import get_internal_number
from plonemeeting.portal.utils import get_next_meeting
from plonemeeting.portal.utils import get_prefixed_gn_position_name
from plonemeeting.portal.utils import get_public_url
from plonemeeting.portal.utils import get_referer_obj
from plonemeeting.portal.utils import getAdvicePortalTypeIds
from plonemeeting.portal.utils import getCurrentMeetingObject
from plonemeeting.portal.utils import is_proposing_group_editor
from plonemeeting.portal.utils import is_transition_before_date
from plonemeeting.portal.utils import isPowerObserverForCfg
from plonemeeting.portal.utils import listifySignatures
from plonemeeting.portal.utils import normalize
from plonemeeting.portal.utils import normalize_id
from plonemeeting.portal.utils import number_word
from plonemeeting.portal.utils import org_id_to_uid
from plonemeeting.portal.utils import reindex_object
from plonemeeting.portal.utils import set_dx_value
from plonemeeting.portal.utils import set_internal_number
from plonemeeting.portal.utils import toHTMLStrikedContent
from plonemeeting.portal.utils import uncapitalize
